import quranData from "../../packages/quran-content/quran.json";
import pagesData from "../../packages/quran-content/pages.json";
import wordTimingData from "../../packages/quran-content/word-timing.json";

export type Ayah = {
  number: number;
  text: string;
  translation: string;
  transliteration: string;
  page: number;
  juz: number;
  audio: string;
};

export type WordTiming = { index: number; text: string; startMs: number; endMs: number };
export type Surah = {
  number: number;
  name: string;
  arabic: string;
  meaning: string;
  type: string;
  ayahs: Ayah[];
};

// Full 114-surah / 6236-ayah Uthmani text, Sahih International translation,
// and transliteration -- generated by scripts/generate-quran-content.mjs from
// the `quran-json` dataset. Page numbers come from `quran-meta` (Hafs riwaya,
// 604-page Madani mushaf layout) -- see packages/quran-content/pages.json.
export const surahs: Surah[] = quranData.surahs;
export const PAGE_COUNT: number = pagesData.pageCount;

const surahByNumber = new Map(surahs.map((surah) => [surah.number, surah]));

export function getSurah(number: number): Surah | undefined {
  return surahByNumber.get(number);
}

export function getAyah(surah: number, ayah: number): Ayah | undefined {
  return getSurah(surah)?.ayahs.find((item) => item.number === ayah);
}

type PageEntry = {
  page: number;
  firstSurah: number;
  firstAyah: number;
  lastSurah: number;
  lastAyah: number;
  ayahs: { surah: number; ayah: number }[];
};

const pageByNumber = new Map((pagesData.pages as PageEntry[]).map((entry) => [entry.page, entry]));

export type MushafPage = { page: number; ayahs: (Ayah & { surah: number })[] };

export function getPage(pageNumber: number): MushafPage | undefined {
  const entry = pageByNumber.get(pageNumber);
  if (!entry) return undefined;
  return {
    page: entry.page,
    ayahs: entry.ayahs
      .map(({ surah, ayah }) => {
        const found = getAyah(surah, ayah);
        return found ? { ...found, surah } : undefined;
      })
      .filter((item): item is Ayah & { surah: number } => Boolean(item)),
  };
}

export function getPageForAyah(surah: number, ayah: number): number | undefined {
  return getAyah(surah, ayah)?.page;
}

// Real per-word audio timing (Alafasy 128kbps, cpfair/quran-align) -- see
// packages/quran-content/README.md. Only present for ayahs whose segment
// data reliably covers every word; missing here means "fall back to
// ayah-level sync", never a guessed alignment.
const wordTimingByAyah = new Map<string, WordTiming[]>(
  Object.entries(wordTimingData.ayahs as Record<string, { i: number; t: string; s: number; e: number }[]>).map(
    ([key, segments]) => [key, segments.map((seg) => ({ index: seg.i, text: seg.t, startMs: seg.s, endMs: seg.e }))],
  ),
);

export function getWordTiming(surah: number, ayah: number): WordTiming[] | undefined {
  return wordTimingByAyah.get(`${surah}:${ayah}`);
}

