"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { surahs } from "@/lib/quran";
import type { VisionResult } from "../../../packages/ai-services/types";

export default function VisionPage() {
  const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | null>(null); const [cameraOn, setCameraOn] = useState(false); const [frame, setFrame] = useState<string>(); const [result, setResult] = useState<VisionResult>(); const [surah, setSurah] = useState("1"); const [ayah, setAyah] = useState("1"); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  useEffect(() => () => stream.current?.getTracks().forEach((track) => track.stop()), []);
  const startCamera = async () => { setError(""); try { stream.current = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: "environment" } }, audio: false }); if (video.current) video.current.srcObject = stream.current; setCameraOn(true); } catch { setError("Camera access was not available. You can still use manual position search below."); } };
  const stopCamera = () => { stream.current?.getTracks().forEach((track) => track.stop()); stream.current = null; setCameraOn(false); };
  const capture = async () => { if (!video.current) return; const canvas = document.createElement("canvas"); canvas.width = video.current.videoWidth; canvas.height = video.current.videoHeight; canvas.getContext("2d")?.drawImage(video.current, 0, 0); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/jpeg", .82)); if (!blob) return; setFrame(URL.createObjectURL(blob)); const response = await fetch("/api/vision", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ imageBytes: blob.size, mimeType: blob.type }) }); const body = await response.json() as { data: VisionResult }; setResult(body.data); stopCamera(); };
  const confirmPosition = () => { const position = { surah: Number(surah), ayah: Number(ayah), source: result?.status === "real" ? "vision" : "manual" }; window.localStorage.setItem("noor:quran-position", JSON.stringify(position)); void fetch("/api/position", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(position) }); setSaved(true); };
  return <main className="page-shell vision-page"><div className="section-heading"><div><p className="eyebrow">QURAN VISION · CAMERA</p><h1>Find your place.</h1><p className="lede">Point your camera at a page, then confirm before Noor saves anything.</p></div><span className="status-pill">{result?.status === "real" ? "REAL" : "OCR · NOT CONFIGURED"}</span></div><section className="vision-layout"><div className="viewfinder glass-card">{cameraOn ? <video ref={video} autoPlay playsInline /> : frame ? <Image src={frame} alt="Captured Quran page" fill unoptimized /> : <div className="viewfinder-empty"><span>▧</span><p>Camera viewfinder</p><small>Use a clear, well-lit Quran page.</small></div>}<div className="viewfinder-corners" />{!cameraOn && !frame && <button className="primary-button camera-button" onClick={startCamera}>Open camera <span>→</span></button>}{cameraOn && <button className="primary-button camera-button" onClick={capture}>Capture frame <span>◉</span></button>}</div><aside className="vision-panel glass-card"><p className="eyebrow">DETECTION</p>{result ? <><div className="detection-empty"><span>○</span><h2>No reliable position found</h2><p>{result.reason}</p></div><p className="privacy-note">The frame was analyzed as a mock request. Nothing moved automatically.</p></> : <><h2>Recognition is not ready</h2><p className="muted">Arabic OCR text matching needs a dedicated OCR runtime and a full licensed Quran corpus. This build does not guess.</p></>}<div className="manual-form"><p className="eyebrow">MANUAL CONFIRMATION</p><label>Surah<select value={surah} onChange={(event) => setSurah(event.target.value)}>{surahs.map((item) => <option value={item.number} key={item.number}>{item.number} · {item.name}</option>)}</select></label><label>Ayah<input type="number" min="1" value={ayah} onChange={(event) => setAyah(event.target.value)} /></label><button className="primary-button" onClick={confirmPosition}>{saved ? "Position saved" : "Confirm this position →"}</button></div></aside></section>{error && <p className="error-text">{error}</p>}<div className="vision-fallback"><Link href="/quran" className="quiet-button">Open Quran reader</Link><p className="privacy-note">Vision never silently changes your Quran position. Only manual confirmation can save a position in this MVP.</p></div></main>;
}
