"use client";
import { useRef, useState, useSyncExternalStore } from "react";
import Link from "next/link";
import { surahs } from "@/lib/quran";
import type { RecitationResult } from "../../../packages/ai-services/types";

export default function RecitationPage() {
  const ayah = surahs[0].ayahs[0]; const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]); const startedAt = useRef(0); const privacy = useSyncExternalStore((onStoreChange) => { window.addEventListener("noor-privacy", onStoreChange); return () => window.removeEventListener("noor-privacy", onStoreChange); }, () => window.localStorage.getItem("noor:voice-privacy-accepted") === "true", () => false); const [recording, setRecording] = useState(false); const [audioUrl, setAudioUrl] = useState<string>(); const [duration, setDuration] = useState(0); const [retention, setRetention] = useState("session"); const [result, setResult] = useState<RecitationResult>(); const [error, setError] = useState("");
  const acceptPrivacy = () => { window.localStorage.setItem("noor:voice-privacy-accepted", "true"); window.dispatchEvent(new Event("noor-privacy")); };
  const startRecording = async () => { setError(""); try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const mediaRecorder = new MediaRecorder(stream); chunks.current = []; startedAt.current = Date.now(); mediaRecorder.ondataavailable = (event) => chunks.current.push(event.data); mediaRecorder.onstop = () => { const blob = new Blob(chunks.current, { type: "audio/webm" }); setAudioUrl(URL.createObjectURL(blob)); stream.getTracks().forEach((track) => track.stop()); }; recorder.current = mediaRecorder; mediaRecorder.start(); setRecording(true); } catch { setError("Microphone access was not available. Check your browser permission and try again."); } };
  const stopRecording = () => { recorder.current?.stop(); setRecording(false); setDuration(Math.max(1, Math.round((Date.now() - startedAt.current) / 1000))); };
  const submit = async () => { if (!audioUrl) return; const response = await fetch("/api/recitation", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ surah: 1, ayah: 1, durationSeconds: Math.max(1, duration), audioBytes: chunks.current.reduce((total, chunk) => total + chunk.size, 0), retention }) }); const body = await response.json() as { data: RecitationResult }; setResult(body.data); };
  const deleteRecordings = () => { setAudioUrl(undefined); setResult(undefined); chunks.current = []; void fetch("/api/recitation", { method: "DELETE" }); };
  if (!privacy) return <main className="page-shell narrow-shell privacy-gate"><div className="auth-mark">◉</div><p className="eyebrow">BEFORE YOUR FIRST RECORDING</p><h1>Your voice stays yours.</h1><p className="lede">Noor needs microphone access to make a recitation recording. Here is exactly what happens:</p><section className="privacy-points glass-card"><p><b>Session-only by default</b><br /><span>Your audio stays in this browser session and is not kept after you leave.</span></p><p><b>You choose retention</b><br /><span>Opt into 7 or 30 days only when you select it. There is no forever option.</span></p><p><b>Delete anytime</b><br /><span>Use Delete my recordings on the coach screen to clear audio and analysis metadata.</span></p></section><button className="primary-button" onClick={acceptPrivacy}>I understand, continue</button></main>;
  return <main className="page-shell narrow-shell"><div className="section-heading"><div><p className="eyebrow">RECITATION COACH · BATCH CHECK</p><h1>Listen. Repeat. Grow.</h1><p className="lede">Al-Fatihah 1:1 · feedback arrives after the full recording.</p></div><span className="status-pill">REAL · BEST-EFFORT</span></div><section className="coach-card glass-card"><div className="reference-row"><div><p className="eyebrow">1 · LISTEN</p><h2>Reference ayah</h2></div><audio controls src={ayah.audio} /></div><div className="record-row"><div><p className="eyebrow">2 · RECORD</p><h2>{recording ? "Listening to you..." : "Your turn"}</h2></div><button className={recording ? "record-button recording" : "record-button"} onClick={recording ? stopRecording : startRecording}>{recording ? "Stop recording" : "● Record"}</button></div>{audioUrl && <div className="playback-row"><p className="eyebrow">3 · PLAYBACK</p><audio controls src={audioUrl} /><label>Keep recording <select value={retention} onChange={(event) => setRetention(event.target.value)}><option value="session">This session only</option><option value="7d">7 days</option><option value="30d">30 days</option></select></label><button className="primary-button" onClick={submit}>Submit for feedback →</button></div>}{error && <p className="error-text">{error}</p>}</section>{result && <section className="feedback-card glass-card"><div className="card-topline"><span>YOUR FEEDBACK</span><span className="weak-status">{result.analysisMode}</span></div><div className="feedback-list">{result.feedback.map((item) => <article key={item.title}><span>✓</span><div><h3>{item.title}</h3><p>{item.detail}</p></div></article>)}</div><div className="retry-row"><Link href="/quran?surah=1&ayah=1" className="quiet-button">Slow mode</Link><button className="primary-button" onClick={() => { setResult(undefined); setAudioUrl(undefined); }}>Try again</button></div></section>}<button className="delete-button" onClick={deleteRecordings}>Delete my recordings</button><p className="privacy-note">Best-effort batch analysis only. Noor does not claim phoneme-level pronunciation scoring without a speech model.</p></main>;
}
